In [1]:
import pandas as pd 
import numpy as np 
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
# Load the dataset
df= pd.read_excel(r'C:\Users\User\Desktop\yield_predictor-1\kenyan_agriculture_yield_dataset_with_season.xlsx')

In [3]:
df.head()

,crop_type,county,season,soil_ph,soil_moisture,fertilizer_usage,temperature,rainfall,altitude,yield
0,Wheat,Kisii,Long Rains,6.312677,16.452090,259.852844,20.297589,319.752769,1700,1039.387999
1,Beans,Kisii,Short Rains,6.035297,19.585113,91.272673,19.424491,7.998039,1700,701.330049
2,Sorghum,Nyeri,Long Rains,6.677663,24.561550,294.969266,16.696070,218.060356,1800,1181.606949
3,Maize,Kakamega,Long Rains,6.576101,24.635413,4.789876,25.993963,205.055409,1530,1533.319182
4,Wheat,Kisii,Long Rains,6.316440,31.563057,93.513323,22.168047,391.698782,1700,1447.687116

In [4]:
df.isna().sum()

crop_type           0
county              0
season              0
soil_ph             0
soil_moisture       0
fertilizer_usage    0
temperature         0
rainfall            0
altitude            0
yield               0
dtype: int64

In [5]:
df.info

<bound method DataFrame.info of      crop_type    county       season   soil_ph  soil_moisture  \
0        Wheat     Kisii   Long Rains  6.312677      16.452090
1        Beans     Kisii  Short Rains  6.035297      19.585113
2      Sorghum     Nyeri   Long Rains  6.677663      24.561550
3        Maize  Kakamega   Long Rains  6.576101      24.635413
4        Wheat     Kisii   Long Rains  6.316440      31.563057
...        ...       ...          ...       ...            ...
1995   Sorghum     Thika   Long Rains  6.457681      29.259803
1996     Maize     Thika   Long Rains  6.877559      22.803470
1997    Millet   Mombasa   Long Rains  7.414134      24.759859
1998   Sorghum      Meru   Long Rains  6.166636      34.723048
1999     Maize    Kisumu   Long Rains  7.119504      18.629093

      fertilizer_usage  temperature    rainfall  altitude        yield
0           259.852844    20.297589  319.752769      1700  1039.387999
1            91.272673    19.424491    7.998039      1700   701.330049
2           294.969266    16.696070  218.060356      1800  1181.606949
3             4.789876    25.993963  205.055409      1530  1533.319182
4            93.513323    22.168047  391.698782      1700  1447.687116
...                ...          ...         ...       ...          ...
1995        135.950428    23.677731  151.406211      1500   759.045296
1996         79.721423    19.029198  110.120836      1500  1430.204490
1997          3.380834    26.965419  149.034334        50   895.455688
1998          1.806612    21.830714  181.527094      1550   223.339529
1999        279.949053    27.005359  301.365078      1131  1624.203764

[2000 rows x 10 columns]>

In [6]:
df.columns

Index(['crop_type', 'county', 'season', 'soil_ph', 'soil_moisture',
       'fertilizer_usage', 'temperature', 'rainfall', 'altitude', 'yield'],
      dtype='object')

In [7]:
df.head()

,crop_type,county,season,soil_ph,soil_moisture,fertilizer_usage,temperature,rainfall,altitude,yield
0,Wheat,Kisii,Long Rains,6.312677,16.452090,259.852844,20.297589,319.752769,1700,1039.387999
1,Beans,Kisii,Short Rains,6.035297,19.585113,91.272673,19.424491,7.998039,1700,701.330049
2,Sorghum,Nyeri,Long Rains,6.677663,24.561550,294.969266,16.696070,218.060356,1800,1181.606949
3,Maize,Kakamega,Long Rains,6.576101,24.635413,4.789876,25.993963,205.055409,1530,1533.319182
4,Wheat,Kisii,Long Rains,6.316440,31.563057,93.513323,22.168047,391.698782,1700,1447.687116

In [8]:
df1 = df.drop(['soil_ph', 'soil_moisture','fertilizer_usage', 'temperature', 'rainfall', 'altitude', 'yield'], axis=1)
df1.head()

  crop_type    county       season
0     Wheat     Kisii   Long Rains
1     Beans     Kisii  Short Rains
2   Sorghum     Nyeri   Long Rains
3     Maize  Kakamega   Long Rains
4     Wheat     Kisii   Long Rains

In [9]:
df.columns

Index(['crop_type', 'county', 'season', 'soil_ph', 'soil_moisture',
       'fertilizer_usage', 'temperature', 'rainfall', 'altitude', 'yield'],
      dtype='object')

In [10]:
# categorical features =crop_type,season,county
from sklearn.preprocessing import OneHotEncoder
encoder = OneHotEncoder()
encoded_features = encoder.fit_transform(df1)
encoded_df = pd.DataFrame(encoded_features.toarray(), columns=encoder.get_feature_names_out(df1.columns))
encoded_df.head()

,crop_type_Beans,crop_type_Maize,crop_type_Millet,crop_type_Sorghum,crop_type_Wheat,county_Eldoret,county_Kakamega,county_Kisii,county_Kisumu,county_Meru,county_Mombasa,county_Nairobi,county_Nakuru,county_Nyeri,county_Thika,season_Long Rains,season_Short Rains
0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
1,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
2,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0
3,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
4,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0

In [11]:
df = pd.concat([encoded_df,df],axis=1)
df.drop(['crop_type', 'season', 'county'], axis=1, inplace=True)
df.columns

Index(['crop_type_Beans', 'crop_type_Maize', 'crop_type_Millet',
       'crop_type_Sorghum', 'crop_type_Wheat', 'county_Eldoret',
       'county_Kakamega', 'county_Kisii', 'county_Kisumu', 'county_Meru',
       'county_Mombasa', 'county_Nairobi', 'county_Nakuru', 'county_Nyeri',
       'county_Thika', 'season_Long Rains', 'season_Short Rains', 'soil_ph',
       'soil_moisture', 'fertilizer_usage', 'temperature', 'rainfall',
       'altitude', 'yield'],
      dtype='object')

In [12]:
df.columns

Index(['crop_type_Beans', 'crop_type_Maize', 'crop_type_Millet',
       'crop_type_Sorghum', 'crop_type_Wheat', 'county_Eldoret',
       'county_Kakamega', 'county_Kisii', 'county_Kisumu', 'county_Meru',
       'county_Mombasa', 'county_Nairobi', 'county_Nakuru', 'county_Nyeri',
       'county_Thika', 'season_Long Rains', 'season_Short Rains', 'soil_ph',
       'soil_moisture', 'fertilizer_usage', 'temperature', 'rainfall',
       'altitude', 'yield'],
      dtype='object')

In [13]:
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split    
x = df.drop('yield', axis=1)
y = df['yield']
x_train, x_test, y_train, y_test = train_test_split(x,y, test_size=0.2, random_state=42)
scaler = StandardScaler()
x_train_scaled = scaler.fit_transform(x_train)
x_test_scaled = scaler.transform(x_test)

In [14]:
from sklearn.ensemble import RandomForestRegressor
model = RandomForestRegressor(max_depth=10, min_samples_leaf=1, min_samples_split=15, n_estimators=400)
model.fit(x_train_scaled, y_train)
model.score(x_test_scaled, y_test)

0.7924153684974403